### ISSUE TITLE
Warn when HPKP report-uri is same origin.

### ISSUE THREAD

**Issue by ScottHelme** [securityheaders/securityheaders-bugs#3]
If pinning checks fail the UA can't send a report to the same host, obviously ;-) 

This should throw a warning.

Example here: https://securityheaders.io/?q=https%3A%2F%2Fdetectify.com&hide=on

Twitter thread and comment from @estark37: https://twitter.com/estark37/status/721399544957779969

**Comment by estark37** [comment]
Yeah, Chrome will just throw out such report-uris. We really need to log a console warning when we do that (and for general HPKP parsing failures).

**Comment by rugk** [comment]
That's bad. In fact the UA should (according to the RFC?) try it again later...

**Comment by ScottHelme** [comment]
This is fixed in test and will hit live Soon(TM).

https://test.securityheaders.io/?q=https%3A%2F%2Fdetectify.com&hide=on
